spring:
  application:
    name: spring-securrity-oauth2-demo
  profiles:
    active:
    - keycloak

server:
  port: 9500

logging:
  level:
    org: 
      springframework:
         security: info
         web: info