
logging:
  level:
    org: 
      springframework:
         security: debug
         web: debug
 
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
      clientId: spring-boot
      clientSecret:
      scope: openid
      clientAuthenticationScheme: header
      preEstablishedRedirectUri: http://localhost:9050/login
      useCurrentUri: false
    resource:
      userInfoUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/userinfo



server:
  port: 9050
spring:
  resources:
    chain:
      enabled: true
      